#!/bin/bash
source pres.sh

header "CHAPTER 0 - Virtualenv"

# ----------- install virtualenv ----------------
cmd "pip install virtualenv"

# ----------- create venvs ----------------------
cmd "virtualenv A"

cmd "virtualenv B"

cmd "ls"

cmd "ls A"

# ------------ ipython clash in A -----------------
cmd "source A/bin/activate"

cmd "pip install ipython" "(A)"

cmd "ipython --version" "(A)"

cmd "pip install setuptools==30.0 six==0.9" "(A)"

cmd "ipython --version" "(A)"

cmd "pip install ipython" "(A)"

# ----------- install old six in B ------------
cmd "source B/bin/activate" "(A)"

cmd "pip install setuptools==30.0 six==0.9" "(B)"

cmd "deactivate"
