#!/bin/bash
actions=0

function clean {
    if test -d $1; then
	echo "rm -rf $1"
	rm -rf $1
	actions=$((( $actions + 1 )))
    fi
}
clean ./aiidaenv
clean ./aiida_core
clean ./aiida-mul
clean ./aiida-verdi
clean ./A
clean ./B

if [[ $actions==0 ]]; then
    echo "nothing to clean up."
fi
